### PR TITLE
remove oauth provider hardcode

### PR DESCRIPTION
**Pull request by eychu**

### CODE REVIEW

**Comment by troggy** [comment]
why this PR still not merged? Does everyone use github only?

**Comment by lynndylanhurley** [comment]
@troggy - There seems to be a conflict with this PR that will need to be resolved. I'll try to get around to this today.

**Comment by troggy** [comment]
It looks like this issue is resolved in master, just isn't published

**Comment by booleanbetrayal** [comment]
@troggy / @lynndylanhurley - I just bumped the version to 0.0.7. Closing this issue ... please let me know if 0.0.7 is still causing you issues and we can re-open.

**Comment by booleanbetrayal** [comment]
Actually, make that 0.0.8 ... the dist files needed rebuilding.

**Comment by lynndylanhurley** [comment]
Thanks @booleanbetrayal!!!

**Comment by booleanbetrayal** [comment]
np!

**Comment by troggy** [comment]
thanks. New npm?

**Comment by booleanbetrayal** [comment]
bower is updated, but I don't currently have access to publish to NPM ... perhaps @lynndylanhurley can help me with that?  =]

**Comment by eychu** [comment]
:confused:

**Comment by booleanbetrayal** [comment]
In the meantime, you can always use the git syntax in npm --

 `"j-toker": "git://github.com/lynndylanhurley/j-toker.git#v0.0.8"`

**Pull request closed without merging**
